#ifndef _winx68k_retrodevice
#define _winx68k_retrodevice

#define RETRO_DEVICE_JOY2CURSOR RETRO_DEVICE_SUBCLASS(RETRO_DEVICE_JOYPAD, 1)
#define RETRO_DEVICE_JOY2NUMPAD RETRO_DEVICE_SUBCLASS(RETRO_DEVICE_JOYPAD, 2)
#define RETRO_DEVICE_CPSF_MD RETRO_DEVICE_SUBCLASS(RETRO_DEVICE_JOYPAD, 3)
#define RETRO_DEVICE_CPSF_SFC RETRO_DEVICE_SUBCLASS(RETRO_DEVICE_JOYPAD, 4)

#endif //_winx68k_keyboard
